spring:
    application:
        name: spring-boot-oauth2-client
    mvc:
        favicon:
            enabled: false
        throw-exception-if-no-handler-found: true
    main:
        banner-mode: 'off'
security:
    oauth2:
        resource:
            filter-order: 3
        client:
            authenticationScheme: header
logging:
    level:
    # org.springframework.security: DEBUG

server:
    port: 8081
    error:
        whitelabel:
            enabled: false

oauth2:
    clientId: sampleclient
    clientSecret: samplepassword
    resourceId: sample-resource
    paths:
        check_token: http://localhost:8080/v1/oauth2/check_token