spring:
    application:
        name: oauth2-client
    mvc:
        favicon:
            enabled: false
        throw-exception-if-no-handler-found: true
    main:
        banner-mode: 'off'
#management:
#    context_path: /admin
security:
    oauth2:
        resource:
            filter-order: 3
        client:
            authenticationScheme: header
logging:
    level:
    # org.springframework.security: DEBUG

server:
    port: 8081
    error:
        whitelabel:
            enabled: false